stages:
  - debug
  - lint
  - build
  - deploy
  -
before_script:
  - apt-get update
  - apt-get -y install npm nodejs
  - npm install # Instnall dependencies before running the jobs

eslint:
  stage: lint
  script:
    - npx eslint . # Run ESLint for linting

build:
  stage: build
  script:
    - npm run build # Command to build your Node.js application

deploy:
  stage: deploy
  script:
    - chmod 600 $AWS_ACCESS_KEY_ID
    - ssh -i $AWS_ACCESS_KEY_ID admin@13.48.138.37 "cd backend && git pull" # SSH into your server and update the app
    - ssh -i $AWS_ACCESS_KEY_ID admin@13.48.138.37 "cd backend && npm install && npm run build && pm2 stop all && pm2 start build/index.js && pm2 save" # Run necessary commands on the server
  only:
    - master # Deploy only when changes are pushed to the master branch

debug:
  stage: debug
  script:
    - cat $AWS_ACCESS_KEY_ID